/*
 * Statistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telemetry.Client.Api;
using Telemetry.Client.Model;
using Telemetry.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telemetry.Client.Test
{
    /// <summary>
    ///  Class for testing AppInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppInfo
        //private AppInfo instance;

        public AppInfoTests()
        {
            // TODO uncomment below to create an instance of AppInfo
            //instance = new AppInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppInfo
        /// </summary>
        [Fact]
        public void AppInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppInfo
            //Assert.IsType<AppInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Fact]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'OsName'
        /// </summary>
        [Fact]
        public void OsNameTest()
        {
            // TODO unit test for the property 'OsName'
        }
        /// <summary>
        /// Test the property 'LastUpdatedAt'
        /// </summary>
        [Fact]
        public void LastUpdatedAtTest()
        {
            // TODO unit test for the property 'LastUpdatedAt'
        }

    }

}
