/*
 * Statistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telemetry.Client.Api;
using Telemetry.Client.Model;
using Telemetry.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telemetry.Client.Test
{
    /// <summary>
    ///  Class for testing AppInfoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppInfoRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppInfoRequest
        //private AppInfoRequest instance;

        public AppInfoRequestTests()
        {
            // TODO uncomment below to create an instance of AppInfoRequest
            //instance = new AppInfoRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppInfoRequest
        /// </summary>
        [Fact]
        public void AppInfoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppInfoRequest
            //Assert.IsType<AppInfoRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AppInfo'
        /// </summary>
        [Fact]
        public void AppInfoTest()
        {
            // TODO unit test for the property 'AppInfo'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

    }

}
