/*
 * Statistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Telemetry.Client.Api;
using Telemetry.Client.Model;
using Telemetry.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Telemetry.Client.Test
{
    /// <summary>
    ///  Class for testing StatisticsEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatisticsEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatisticsEvent
        //private StatisticsEvent instance;

        public StatisticsEventTests()
        {
            // TODO uncomment below to create an instance of StatisticsEvent
            //instance = new StatisticsEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatisticsEvent
        /// </summary>
        [Fact]
        public void StatisticsEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatisticsEvent
            //Assert.IsType<StatisticsEvent>(instance);
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
