version: "3"
services:
    api:
        build:
            context: ./NetCoreApiLinux
            dockerfile: ./NetCoreApiLinux/Dockerfile
        image: aspnetapp
        environment:
          - ASPNETCORE_URLS=http://+:80
          - MongoDbSettings__Host=mongo
          - MongoDbSettings__Port=27017
    front:
        build: 
            context: ./telemetry-app
            args:
                env: prod
        image: telemetry-app
        container_name: front
        links:
          - api
        ports:
          - "82:443"
          
    seq:
        image: datalust/seq:latest
        environment:
          - ACCEPT_EULA=Y
        volumes:
          - ./logs:/data
        ports:
          - "84:80"
          - "5342:5341"
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27018:27017