version: "3"
services:
    api:
        build:
            context: ./NetCoreApiLinux
            dockerfile: ./NetCoreApiLinux/Dockerfile
        image: aspnetapp
        environment:
          - ASPNETCORE_URLS=http://+:80
          - MongoDbSettings__Host=mongo
          - MongoDbSettings__Port=27017
    front:
        build: 
            context: ./telemetry-app
            args:
                env: prod
        image: telemetry-app
        container_name: front
        links:
          - api
        ports:
          - "82:443"
          
    seq:
        image: datalust/seq:latest
        environment:
          - ACCEPT_EULA=Y
        volumes:
          - ./logs:/data
        ports:
          - "84:80"
          - "5342:5341"
    mongo:
        image: mongo
        hostname: mongo
        command: --replSet telemetry-rs
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: Telemetry
            MONGO_REPLICA_SET_NAME: telemetry-rs
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u root -p example --quiet) -eq 1
            timeout: 5s
            interval: 10s
        ports:
          - 27018:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8083:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
          - mongo
