version: "3"
services:
    api:
        build:
            context: ./NetCoreApiLinux
            dockerfile: ./NetCoreApiLinux/Dockerfile
        image: aspnetapp
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:80

    front:
        build: 
            context: ./telemetry-app
            args:
                env: prod            
        image: telemetry-app
        container_name: front
        links:
          - api
        ports:
          - "82:443"