version: '3.4'

services:
    tests:
        image: datalayertests
        build:
            context: ../
            dockerfile: DataLayer.IntegrationTests/Dockerfile
        environment:
          MongoDbSettings__Host: mongo
          MongoDbSettings__Port: 27017
        stdin_open: true # docker run -i
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27018:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8082:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
          - mongo
