version: '3.5'

services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27018:27017
        networks:
          - my-network-name
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8082:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
          - mongo
        networks:
          - my-network-name
networks:
  my-network-name:
   name: custom_network